### ISSUE TITLE
Contents / cards do not get synchronized

### ISSUE THREAD

**Issue by selmaohneh** [corvec/sn-kanban-editor#2]
Just tried out the editor on mobile and added some lanes and cards.
After switching to my desktop the note opens with an empty board.
I guess the synchronzing does not yet work?

**Comment by selmaohneh** [comment]
EDIT: The content seems to be there, since I can see the tip of it inside the preview of the note. Still, they are not rendered as board / the board stays empty.

**Comment by corvec** [comment]
I believe the issue was because v0.2.0 only supported the JSON format used by the react-trello lib, but in v0.3.0 I've switched to Markdown. I failed to update the ext.json and for the download URL it was pointing to the v0.2.0 release.

I've tested this in my local install and it seems to be working fine. You may need to uninstall and reinstall the Extension but it should handle that automatically.

**Comment by selmaohneh** [comment]
Yep, works now. Thanks.
